build:
	go build -v -o bin/oom-certservice-k8s-external-provider

build-docker-image:
	docker build -t onap/oom-certservice-k8s-external-provider .

run-docker-image:
	docker run -it onap/oom-certservice-k8s-external-provider

