/*
 * ============LICENSE_START=======================================================
 * oom-certservice-k8s-external-provider
 * ================================================================================
 * Copyright (c) 2019 Smallstep Labs, Inc.
 * Modifications copyright (C) 2020 Nokia. All rights reserved.
 * ================================================================================
 * This source code was copied from the following git repository:
 * https://github.com/smallstep/step-issuer
 * The source code was modified for usage in the ONAP project.
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END=========================================================
 */

package api

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (inputSecretKeySelector *SecretKeySelector) DeepCopyInto(outSecretKeySelector *SecretKeySelector) {
	*outSecretKeySelector = *inputSecretKeySelector
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (inputSecretKeySelector *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if inputSecretKeySelector == nil {
		return nil
	}
	out := new(SecretKeySelector)
	inputSecretKeySelector.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (inputCertServiceIssuer *CertServiceIssuer) DeepCopyInto(outCertServiceIssuer *CertServiceIssuer) {
	*outCertServiceIssuer = *inputCertServiceIssuer
	outCertServiceIssuer.TypeMeta = inputCertServiceIssuer.TypeMeta
	inputCertServiceIssuer.ObjectMeta.DeepCopyInto(&outCertServiceIssuer.ObjectMeta)
	inputCertServiceIssuer.Spec.DeepCopyInto(&outCertServiceIssuer.Spec)
	inputCertServiceIssuer.Status.DeepCopyInto(&outCertServiceIssuer.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertServiceIssuer.
func (inputCertServiceIssuer *CertServiceIssuer) DeepCopy() *CertServiceIssuer {
	if inputCertServiceIssuer == nil {
		return nil
	}
	out := new(CertServiceIssuer)
	inputCertServiceIssuer.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (inputCertServiceIssuer *CertServiceIssuer) DeepCopyObject() runtime.Object {
	if deepCopy := inputCertServiceIssuer.DeepCopy(); deepCopy != nil {
		return deepCopy
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (inputIssuerCondition *CertServiceIssuerCondition) DeepCopyInto(outIssuerCondition *CertServiceIssuerCondition) {
	*outIssuerCondition = *inputIssuerCondition
	if inputIssuerCondition.LastTransitionTime != nil {
		in, out := &inputIssuerCondition.LastTransitionTime, &outIssuerCondition.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertServiceIssuerCondition.
func (inputIssuerCondition *CertServiceIssuerCondition) DeepCopy() *CertServiceIssuerCondition {
	if inputIssuerCondition == nil {
		return nil
	}
	out := new(CertServiceIssuerCondition)
	inputIssuerCondition.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (inputIssuerList *CertServiceIssuerList) DeepCopyInto(outIssuerList *CertServiceIssuerList) {
	*outIssuerList = *inputIssuerList
	outIssuerList.TypeMeta = inputIssuerList.TypeMeta
	inputIssuerList.ListMeta.DeepCopyInto(&outIssuerList.ListMeta)
	if inputIssuerList.Items != nil {
		in, out := &inputIssuerList.Items, &outIssuerList.Items
		*out = make([]CertServiceIssuer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertServiceIssuerList.
func (inputIssuerList *CertServiceIssuerList) DeepCopy() *CertServiceIssuerList {
	if inputIssuerList == nil {
		return nil
	}
	out := new(CertServiceIssuerList)
	inputIssuerList.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (inputIssuerList *CertServiceIssuerList) DeepCopyObject() runtime.Object {
	if deepCopy := inputIssuerList.DeepCopy(); deepCopy != nil {
		return deepCopy
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (inputIssuerSpec *CertServiceIssuerSpec) DeepCopyInto(outIssuerSpec *CertServiceIssuerSpec) {
	*outIssuerSpec = *inputIssuerSpec
	outIssuerSpec.KeyRef = inputIssuerSpec.KeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertServiceIssuerSpec.
func (inputIssuerSpec *CertServiceIssuerSpec) DeepCopy() *CertServiceIssuerSpec {
	if inputIssuerSpec == nil {
		return nil
	}
	out := new(CertServiceIssuerSpec)
	inputIssuerSpec.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (inputIssuerStatus *CertServiceIssuerStatus) DeepCopyInto(outIssuerStatus *CertServiceIssuerStatus) {
	*outIssuerStatus = *inputIssuerStatus
	if inputIssuerStatus.Conditions != nil {
		in, out := &inputIssuerStatus.Conditions, &outIssuerStatus.Conditions
		*out = make([]CertServiceIssuerCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertServiceIssuerStatus.
func (inputIssuerStatus *CertServiceIssuerStatus) DeepCopy() *CertServiceIssuerStatus {
	if inputIssuerStatus == nil {
		return nil
	}
	out := new(CertServiceIssuerStatus)
	inputIssuerStatus.DeepCopyInto(out)
	return out
}
